require:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-rbs

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'ika3.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15
  CountAsOne: ["array", "hash", "heredoc"]

Rbs/MethodSignature:
  Exclude:
    - 'lib/ika3/schedule.rb'

Style/Documentation:
  Enabled: false
