require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'ika3.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Max: 5

Style/Documentation:
  Enabled: false
