plugins:
  - rubocop-rspec
  - rubocop-rake

require:
  - rubocop-on-rbs

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

RBS:
  Enabled: true

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'ika3.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15
  CountAsOne: ["array", "hash", "heredoc"]

Style/Documentation:
  Enabled: false
