extends: default

rules:
  document-start: disable
  comments: disable
  new-line-at-end-of-file:
    level: warning
  truthy: disable
  line-length:
    max: 120

ignore:
  - .gem_rbs_collection/
  - rbs_collection.lock.yaml
