# frozen_string_literal: true

module Ika3
  class Response
    @raw_body: String
    @raw_headers: untyped
    @raw_status: Integer
    @headers: untyped

    def initialize: (Faraday::Response) -> void
    def body: () -> untyped
    def headers: () -> untyped
    def status: () -> Integer
  end
end