class ::Hash[unchecked out K, unchecked out V]
  def respond_to_missing?: (untyped name) -> untyped

  def method_missing: (::Symbol) -> untyped
end

module Ika3
  class Schedule
    @contact: String

    @splat3_connection: untyped

    def initialize: (String) -> void

    private

    def send_request: (Symbol, String) -> untyped

    def api_url: () -> "https://spla3.yuu26.com/"

    def splat3_connection: () -> untyped

    def faraday_options: () -> { url: String, headers: { :"User-Agent" => ::String } }
  end
end
