version: 2.1

orbs:
  ruby: circleci/ruby@2.1.2
  python: circleci/python@2.1.1
  slack: circleci/slack@4.13.2

cop_steps: &cop_steps
  - checkout
  - ruby/install-deps
  - ruby/rubocop-check

spec_steps: &spec_steps
  - checkout
  - ruby/install-deps
  - run:
      name: run rspec
      command: bundle e rspec

spell_check_steps: &spell_check_steps
  - checkout
  - run:
      name: upgrade pip
      command: pip install --upgrade pip
  - run:
      name: install codespell
      command: pip install codespell
  - run:
      name: check spelling with codespell
      command: codespell

slack_steps: &slack_steps
  - checkout
  - slack/notify:
      event: fail
      template: basic_fail_1
  - slack/notify:
      event: pass
      template: basic_success_1

jobs:
  ruby-30-spec:
    executor:
      name: ruby/default
      tag: "3.0"
    steps: *spec_steps
  ruby-31-spec:
    executor:
      name: ruby/default
      tag: "3.1"
    steps: *spec_steps
  ruby-32-spec:
    executor:
      name: ruby/default
      tag: "3.2"
    steps: *spec_steps
  ruby-33-spec:
    executor:
      name: ruby/default
      tag: "3.3"
    steps: *spec_steps
  cop:
    executor:
      name: ruby/default
      tag: "3.3"
    steps: *cop_steps
  spell-check:
    executor:
      name: python/default
      tag: "3.12"
    steps: *spell_check_steps
  slack:
    executor:
      name: ruby/default
      tag: "3.2"
    steps: *slack_steps

workflows:
  build:
    jobs:
      - ruby-30-spec
      - ruby-31-spec
      - ruby-32-spec
      - ruby-33-spec
      - cop
      - spell-check
      - slack:
          requires:
            - ruby-30-spec
            - ruby-31-spec
            - ruby-32-spec
            - ruby-33-spec
            - cop
            - spell-check
          context:
            - slack
