version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  slack: circleci/slack@4.10.1

spec_steps: &spec_steps
  - checkout
  - run: bundle install
  - run:
      name: run rspec
      command: bundle e rspec

slack_steps: &slack_steps
  - checkout
  - slack/notify:
      event: fail
      template: basic_fail_1
  - slack/notify:
      event: pass
      template: basic_success_1

jobs:
  ruby-27-spec:
    docker:
      - image: cimg/ruby:2.7
    executor: ruby/default
    steps: *spec_steps
  ruby-30-spec:
    docker:
      - image: cimg/ruby:3.0
    executor: ruby/default
    steps: *spec_steps
  ruby-31-spec:
    docker:
      - image: cimg/ruby:3.1
    executor: ruby/default
    steps: *spec_steps
  ruby-32-spec:
    docker:
      - image: cimg/ruby:3.2
    executor: ruby/default
    steps: *spec_steps
  slack:
    docker:
      - image: cimg/ruby:3.1
    executor: ruby/default
    steps: *slack_steps

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - ruby-27-spec
      - ruby-30-spec
      - ruby-31-spec
      - ruby-32-spec
      - slack:
          requires:
            - ruby-27-spec
            - ruby-30-spec
            - ruby-31-spec
            - ruby-32-spec
          context:
            - slack
