sploosh_o_matic: &sploosh_o_matic
  name: ボールドマーカー
  sub: カーリングボム
  special: ウルトラハンコ

neo_sploosh_o_matic: &neo_sploosh_o_matic
  name: ボールドマーカーネオ
  sub: ジャンプビーコン
  special: メガホンレーザー5.1ch

splattershot_jr: &splattershot_jr
  name: わかばシューター
  sub: スプラボム
  special: グレートバリア

custom_splattershot_jr: &custom_splattershot_jr
  name: もみじシューター
  sub: トーピード
  special: ホップソナー

splash_o_matic: &splash_o_matic
  name: シャープマーカー
  sub: クイックボム
  special: カニタンク

neo_splash_o_matic: &neo_splash_o_matic
  name: シャープマーカーネオ
  sub: キューバンボム
  special: トリプルトルネード

aerosparay_mg: &aerosparay_mg
  name: プロモデラーMG
  sub: タンサンボム
  special: サメライド

aerosparay_rg: &aerosparay_rg
  name: プロモデラーRG
  sub: スプリンクラー
  special: ナイスダマ

splattershot: &splattershot
  name: スプラシューター
  sub: キューバンボム
  special: ウルトラショット

tentatek_splattershot: &tentatek_splattershot
  name: スプラシューターコラボ
  sub: スプラボム
  special: トリプルトルネード

52_gal: &52_gal
  name: .52ガロン
  sub: スプラッシュシールド
  special: メガホンレーザー5.1ch

52_gal_deco: &52_gal_deco
  name: .52ガロンデコ
  sub: カーリングボム
  special: メガホンレーザー5.1ch

n_zap_85: &n_zap_85
  name: N-ZAP '85
  sub: キューバンボム
  special: エナジースタンド

n_zap_89: &n_zap_89
  name: N-ZAP '89
  sub: ロボットボム
  special: デコイチラシ

splattershot_pro: &splattershot_pro
  name: プライムシューター
  sub: ラインマーカー
  special: カニタンク

forge_splattershot_pro: &forge_splattershot_pro
  name: プライムシューターコラボ
  sub: キューバンボム
  special: ナイスダマ

96_gal: &96_gal
  name: .96ガロン
  sub: スプリンクラー
  special: キューインキ

96_gal_deco: &96_gal_deco
  name: .96ガロンデコ
  sub: スプラッシュシールド
  special: テイオウイカ

jet_squelcher: &jet_squelcher
  name: ジェットスイーパー
  sub: ラインマーカー
  special: キューインキ

custom_jet_squelcher: &custom_jet_squelcher
  name: ジェットスイーパーカスタム
  sub: ポイズンミスト
  special: アメフラシ

l_3_nozzlenose: &l_3_nozzlenose
  name: L3リールガン
  sub: カーリングボム
  special: カニタンク

l_3_nozzlenose_d: &l_3_nozzlenose
  name: L3リールガンD
  sub: クイックボム
  special: ウルトラハンコ

h_3_nozzlenose: &h_3_nozzlenose
  name: H3リールガン
  sub: ポイントセンサー
  special: エナジースタンド

h_3_nozzlenose_d: &h_3_nozzlenose_d
  name: H3リールガンD
  sub: スプラッシュシールド
  special: グレートバリア

squeezer: &squeezer
  name: ボトルガイザー
  sub: スプラッシュシールド
  special: ウルトラショット

foil_squeezer: &foil_squeezer
  name: ボトルガイザーフォイル
  sub: ロボットボム
  special: スミナガシート

splattershot_nova: &splattershot_nova
  name: スペースシューター
  sub: ポイントセンサー
  special: メガホンレーザー5.1ch

annaki_splattershot_nova: &annaki_splattershot_nova
  name: スペースシューターコラボ
  sub: トラップ
  special: ジェットパック

carbon_roller: &carbon_roller
  name: カーボンローラー
  sub: ロボットボム
  special: ショクワンダー

carbon_roller_deco: &carbon_roller_deco
  name: カーボンローラーデコ
  sub: クイックボム
  special: ウルトラショット

splatroller: &splatroller
  name: スプラローラー
  sub: カーリングボム
  special: グレートバリア

krak_on_splatroller: &krak_on_splatroller
  name: スプラローラーコラボ
  sub: ジャンプビーコン
  special: テイオウイカ

dynamo_roller: &dynamo_roller
  name: ダイナモローラー
  sub: スプリンクラー
  special: エナジースタンド

gold_dynamo_roller: &gold_dynamo_roller
  name: ダイナモローラーテスラ
  sub: スプラッシュボム
  special: デコイチラシ

flingza_roller: &flingza_roller
  name: ヴァリアブルローラー
  sub: トラップ
  special: マルチミサイル

foil_flingza_roller: &foil_flingza_roller
  name: ヴァリアブルローラーフォイル
  sub: キューバンボム
  special: スミナガシート

big_swig_roller: &big_swig_roller
  name: ワイドローラー
  sub: スプラッシュシールド
  special: キューインキ

big_swig_roller_express: &big_swig_roller_express
  name: ワイドローラーコラボ
  sub: ラインマーカー
  special: アメフラシ

classic_squiffer: &classic_squiffer
  name: スクイックリン
  sub: ポイントセンサー
  special: グレートバリア

new_squiffer: &new_squiffer
  name: スクイックリンβ
  sub: ロボットボム
  special: ショクワンダー

splat_charger: &splat_charger
  name: スプラチャージャー
  sub: スプラボム
  special: キューインキ

z_f_splat_charger: &z_f_splat_charger
  name: スプラチャージャーコラボ
  sub: スプラッシュシールド
  special: トリプルトルネード

splatterscope: &splatterscope
  name: スプラスコープ
  sub: スプラボム
  special: キューインキ

z_f_splatterscope: &z_f_splatterscope
  name: スプラスコープコラボ
  sub: スプラッシュシールド
  special: トリプルトルネード

e_liter_4k: &e_liter_4k
  name: リッター4K
  sub: トラップ
  special: ホップソナー

custom_e_liter_4k: &custom_e_liter_4k
  name: リッター4Kカスタム
  sub: ジャンプビーコン
  special: テイオウイカ

e_liter_4K_scope: &e_liter_4K_scope
  name: 4Kスコープ
  sub: トラップ
  special: ホップソナー

custom_e_liter_4k_scope: &custom_e_liter_4k_scope
  name: 4Kスコープカスタム
  sub: ジャンプビーコン
  special: テイオウイカ


bamboozler_14_mk_1: &bamboozler_14_mk_1
  name: 14式竹筒銃・甲
  sub: ロボットボム
  special: メガホンレーザー5.1ch

bamboozler_14_mk_2: &bamboozler_14_mk_2
  name: 14式竹筒銃・乙
  sub: タンサンボム
  special: デコイチラシ

goo_tuber: &goo_tuber
  name: ソイチューバー
  sub: トーピード
  special: マルチミサイル

custom_goo_tuber: &custom_goo_tuber
  name: ソイチューバーカスタム
  sub: タンサンボム
  special: ウルトラハンコ

snipewriter_5h: &snipewriter_5h
  name: R-PEN/5H
  sub: スプリンクラー
  special: エナジースタンド

snipewriter_5b: &snipewriter_5b
  name: R-PEN/5B
  sub: スプラッシュシールド
  special: アメフラシ

slosher: &slosher
  name: バケットスロッシャー
  sub: キューバンボム
  special: トリプルトルネード

slosher_deco: &slosher_deco
  name: バケットスロッシャーデコ
  sub: ラインマーカー
  special: ショクワンダー

tri_slocher: &tri_slocher
  name: ヒッセン
  sub: ポイズンミスト
  special: ジェットパック

tri_slosher_nouveau: &tri_slosher_nouveau
  name: ヒッセン・ヒュー
  sub: タンサンボム
  special: エナジースタンド

sloshing_machine: &sloshing_machine
  name: スクリュースロッシャー
  sub: タンサンボム
  special: ナイスダマ

sloshing_machine_neo: &sloshing_machine_neo
  name: スクリュースロッシャーネオ
  sub: ポイントセンサー
  special: ウルトラショット

bloblobber: &bloblobber
  name: オーバーフロッシャー
  sub: スプリンクラー
  special: アメフラシ

bloblobber_deco: &bloblobber_deco
  name: オーバーフロッシャーデコ
  sub: ラインマーカー
  special: テイオウイカ

explosher: &explosher
  name: エクスプロッシャー
  sub: ポイントセンサー
  special: アメフラシ

custom_explosher: &custom_explosher
  name: エクスプロッシャーカスタム
  sub: スプラッシュシールド
  special: ウルトラチャクチ

dread_wringer: &dread_wringer
  name: モップリン
  sub: キューバンボム
  special: サメライド

dread_wringer_d: &dread_wringer_d
  name: モップリンD
  sub: ジャンプビーコン
  special: ホップソナー

mini_splatling: &mini_splatling
  name: スプラスピナー
  sub: クイックボム
  special: ウルトラハンコ

zink_mini_splatling: &zink_mini_splatling
  name: スプラスピナーコラボ
  sub: ポイズンミスト
  special: グレートバリア

heavy_splatling: &heavy_splatling
  name: バレルスピナー
  sub: スプリンクラー
  special: ホップソナー

heavy_splatling_deco: &heavy_splatling
  name: バレルスピナーデコ
  sub: ポイントセンサー
  special: テイオウイカ

hydra_splatling: &hydra_splatling
  name: ハイドラント
  sub: ロボットボム
  special: ナイスダマ

custom_hydra_splatling: &custom_hydra_splatling
  name: ハイドラントカスタム
  sub: トラップ
  special: スミナガシート

ballpoint_splatling: &ballpoint_splatling
  name: クーゲルシュライバー
  sub: タンサンボム
  special: ジェットパック

ballpoint_splatling_nouveas: &ballpoint_splatling_nouveas
  name: クーゲルシュライバー・ヒュー
  sub: トラップ
  special: キューインキ

nautilus_47: &nautilus_47
  name: ノーチラス47
  sub: ポイントセンサー
  special: アメフラシ

nautilus_79: &nautilus_79
  name: ノーチラス79
  sub: キューバンボム
  special: ウルトラチャクチ

heavy_edit_splatling: &heavy_edit_splatling
  name: イグザミナー
  sub: カーリングボム
  special: エナジースタンド

heavy_edit_splatling_nouveau: &heavy_edit_splatling_nouveau
  name: イグザミナー・ヒュー
  sub: スプラッシュボム
  special: カニタンク

luna_blaster: &luna_blaster
  name: ノヴァブラスター
  sub: スプラボム
  special: ショクワンダー

luna_blaster_neo: &luna_blaster_neo
  name: ノヴァブラスターネオ
  sub: タンサンボム
  special: ウルトラハンコ

blaster: &blaster
  name: ホットブラスター
  sub: ロボットボム
  special: グレートバリア

custom_blaster: &custom_blaster
  name: ホットブラスターカスタム
  sub: ポイントセンサー
  special: ウルトラチャクチ

range_blaster: &range_blaster
  name: ロングブラスター
  sub: キューバンボム
  special: ホップソナー

custom_range_blaster: &custom_range_blaster
  name: ロングブラスターカスタム
  sub: スプラッシュボム
  special: テイオウイカ

clash_blaster: &clash_blaster
  name: クラッシュブラスター
  sub: スプラボム
  special: ウルトラショット

clash_blaster_neo: &clash_blaster_neo
  name: クラッシュブラスターネオ
  sub: カーリングボム
  special: デコイチラシ

rapid_blaster: &rapid_blaster
  name: ラピッドブラスター
  sub: トラップ
  special: トリプルトルネード

rapid_blaster_deco: &rapid_blaster_deco
  name: ラピッドブラスターデコ
  sub: トーピード
  special: ジェットパック

rapid_blaster_pro: &rapid_blaster_pro
  name: Rブラスターエリート
  sub: ポイズンミスト
  special: キューインキ

rapid_blaster_pro_deco: &rapid_blaster_pro_deco
  name: Rブラスターエリートデコ
  sub: ラインマーカー
  special: メガホンレーザー5.1ch

s_brast_92: &s_brast_92
  name: S-BRAST92
  sub: スプリンクラー
  special: サメライド

s_brast_91: &s_brast_91
  name: S-BRAST91
  sub: クイックボム
  special: ナイスダマ

splat_brella: &splat_brella
  name: パラシェルター
  sub: スプリンクラー
  special: トリプルトルネード

sorella_brella: &sorella_brella
  name: パラシェルターソレーラ
  sub: ロボットボム
  special: ジェットパック

tenta_brella: &tenta_brella
  name: キャンピングシェルター
  sub: ジャンプビーコン
  special: キューインキ

tenta_sorella_brella: &tenta_sorella_brella
  name: キャンピングシェルターソレーラ
  sub: トラップ
  special: ウルトラショット

recycled_brella_24_mk_1: &recycled_brella_24_mk_1
  name: 24式張替傘・甲
  sub: ラインマーカー
  special: グレートバリア

recycled_brella_24_mk_2: &recycled_brella_24_mk_2
  name: 24式張替傘・乙
  sub: ポイズンミスト
  special: ウルトラチャクチ

undercover_brella: &undercover_brella
  name: スパイガジェット
  sub: トラップ
  special: サメライド

undercover_sorella_brella: &undercover_sorella_brella
  name: スパイガジェットソレーラ
  sub: トーピード
  special: スミナガシート

inkbrush: &inkbrush
  name: パブロ
  sub: スプラボム
  special: メガホンレーザー5.1ch

inkbrush_nouveas: &inkbrush_nouveas
  name: パブロ・ヒュー
  sub: トラップ
  special: ウルトラハンコ

octobrush: &octobrush
  name: ホクサイ
  sub: キューバンボム
  special: ショクワンダー

octobrush_nouveas: &octobrush_nouveas
  name: ホクサイ・ヒュー
  sub: ジャンプビーコン
  special: アメフラシ

painbrush: &painbrush
  name: フィンセント
  sub: カーリングボム
  special: ホップソナー

painbrush_nouveas: &painbrush_nouveas
  name: フィンセント・ヒュー
  sub: ポイントセンサー
  special: マルチミサイル

dapple_dualies: &dapple_dualies
  name: スパッタリー
  sub: ジャンプビーコン
  special: エナジースタンド

dapple_dualies_nouveas: &dapple_dualies_nouveas
  name: スパッタリー・ヒュー
  sub: トーピード
  special: サメライド

splat_dualies: &splat_dualies
  name: スプラマニューバー
  sub: キューバンボム
  special: カニタンク

enperry_splat_dualies: &enperry_splat_dualies
  name: スプラマニューバーコラボ
  sub: カーリングボム
  special: ウルトラチャクチ

dark_tetra_dualies: &dark_tetra_dualies
  name: クアッドホッパーブラック
  sub: ロボットボム
  special: サメライド

light_tetra_dualies: &light_tetra_dualies
  name: クアッドホッパーホワイト
  sub: スプリンクラー
  special: ショクワンダー

dualie_squelchers: &dualie_squelchers
  name: デュアルスイーパー
  sub: スプラボム
  special: ホップソナー

custom_dualie_squelchers: &custom_dualie_squelchers
  name: デュアルスイーパーカスタム
  sub: ジャンプビーコン
  special: デコイチラシ

glooga_dualies: &glooga_dualies
  name: ケルビン525
  sub: スプラッシュシールド
  special: ナイスダマ

glooga_dualies_deco: &glooga_dualies_deco
  name: ケルビン525デコ
  sub: ポイントセンサー
  special: ウルトラショット

douser_dualies_ff: &douser_dualies_ff
  name: ガエンFF
  sub: トラップ
  special: メガホンレーザー5.1ch

custom_douser_dualies_ff: &custom_douser_dualies_ff
  name: ガエンFFカスタム
  sub: クイックボム
  special: トリプルトルネード

tri_stringer: &tri_stringer
  name: トライストリンガー
  sub: ポイズンミスト
  special: メガホンレーザー5.1ch

inkline_tri_stringer: &inkline_tri_stringer
  name: トライストリンガーコラボ
  sub: スプリンクラー
  special: デコイチラシ

reef_lux_450: &reef_lux_450
  name: LACT-450
  sub: カーリングボム
  special: マルチミサイル

reef_lux_450_deco: &reef_lux_450_deco
  name: LACT-450デコ
  sub: スプラッシュシールド
  special: サメライド

wellstring_v: &wellstring_v
  name: フロイドV
  sub: ロボットボム
  special: ウルトラハンコ

custom_wellstring_v: &custom_wellstring_v
  name: フロイドVカスタム
  sub: ポイントセンサー
  special: ホップソナー

splatana_stamper: &splatana_stamper
  name: ジムワイパー
  sub: クイックボム
  special: ショクワンダー

neo_splatana_stamper: &neo_splatana_stamper
  name: ジムワイパー・ヒュー
  sub: ポイズンミスト
  special: カニタンク

splatana_wiper: &splatana_wiper
  name: ドライブワイパー
  sub: トーピード
  special: ウルトラハンコ

splatana_wiper_deco: &splatana_wiper_deco
  name: ドライブワイパーデコ
  sub: ジャンプビーコン
  special: マルチミサイル

mint_decavitator: &mint_decavitator
  name: デンタルワイパーミント
  sub: キューバンボム
  special: グレートバリア

charcoal_decavitator: &charcoal_decavitator
  name: デンタルワイパースミ
  sub: スプラッシュシールド
  special: ジェットパック
