sploosh_o_matic: &sploosh_o_matic
  name: ボールドマーカー
  sub: カーリングボム
  special: ウルトラハンコ

neo_sploosh_o_matic: &neo_sploosh_o_matic
  name: ボールドマーカーネオ
  sub: ジャンプビーコン
  special: メガホンレーザー5.1ch

splattershot_jr: &splattershot_jr
  name: わかばシューター
  sub: スプラボム
  special: グレートバリア

custom_splattershot_jr: &custom_splattershot_jr
  mame: もみじシューター
  sub: トーピード
  special: ホップソナー

splash_o_matic: &splash_o_matic
  name: シャープマーカー
  sub: クイックボム
  special: カニタンク

neo_splash_o_matic: &neo_splash_o_matic
  name: シャープマーカーネオ
  sub: キューバンボム
  special: トリプルトルネード

aerosparay_mg: &aerosparay_mg
  name: プロモデラーMG
  sub: タンサンボム
  special: サメライド

aerosparay_rg: &aerosparay_rg
  name: プロモデラーRG
  sub: スプリンクラー
  special: ナイスダマ

splattershot: &splattershot
  name: スプラシューター
  sub: キューバンボム
  special: ウルトラショット

tentatek_splattershot: &tentatek_splattershot
  name: スプラシューターコラボ
  sub: スプラボム
  special: トリプルトルネード

52_gal: &52_gal
  name: .52ガロン
  sub: スプラッシュシールド
  special: メガホンレーザー5.1ch

n_zap_85: &n_zap_85
  name: N-ZAP '85
  sub: キューバンボム
  special: エナジースタンド

n_zap_89: &n_zap_89
  name: N-ZAP '89
  sub: ロボットボム
  special: デコイチラシ

splattershot_pro: &splattershot_pro
  name: プライムシューター
  sub: ラインマーカー
  special: カニタンク

forge_splattershot_pro: &forge_splattershot_pro
  name: プライムシューターコラボ
  sub: キューバンボム
  special: ナイスダマ

96_gal: &96_gal
  name: .96ガロン
  sub: スプリンクラー
  special: キューインキ

96_gal_deco: &96_gal_deco
  name: .96ガロンデコ
  sub: スプラッシュシールド
  special: テイオウイカ

jet_squelcher: &jet_squelcher
  name: ジェットスイーパー
  sub: ラインマーカー
  special: キューインキ

custom_jet_squelcher: &custom_jet_squelcher
  name: ジェットスイーパーカスタム
  sub: ポイズンミスト
  special: アメフラシ

l_3_nozzlenose: &l_3_nozzlenose
  name: L3リールガン
  sub: カーリングボム
  special: カニタンク

l_3_nozzlenose_d: &l_3_nozzlenose
  name: L3リールガンD
  sub: クイックボム
  special: ウルトラハンコ

h_3_nozzlenose: &h_3_nozzlenose
  name: H3リールガン
  sub: ポイントセンサー
  special: エナジースタンド

squeezer: &squeezer
  name: ボトルガイザー
  sub: スプラッシュシールド
  special: ウルトラショット

splattershot_nova: &splattershot_nova
  name: スペースシューター
  sub: ポイントセンサー
  special: メガホンレーザー5.1ch

carbon_roller: &carbon_roller
  name: カーボンローラー
  sub: ロボットボム
  special: ショクワンダー

carbon_roller_deco: &carbon_roller_deco
  name: カーボンローラーデコ
  sub: クイックボム
  special: ウルトラショット

splatroller: &splatroller
  name: スプラローラー
  sub: カーリングボム
  special: グレートバリア

krak_on_splatroller: &krak_on_splatroller
  name: スプラローラーコラボ
  sub: ジャンプビーコン
  special: テイオウイカ

dynamo_roller: &dynamo_roller
  name: ダイナモローラー
  sub: スプリンクラー
  special: エナジースタンド

flingza_roller: &flingza_roller
  name: ヴァリアブルローラー
  sub: トラップ
  special: マルチミサイル

big_swig_roller: &big_swig_roller
  name: ワイドローラー
  sub: スプラッシュシールド
  special: キューインキ

classic_squiffer: &classic_squiffer
  name: スクイックリン
  sub: ポイントセンサー
  special: グレートバリア

splat_charger: &splat_charger
  name: スプラチャージャー
  sub: スプラボム
  special: キューインキ

z_f_splat_charger: &z_f_splat_charger
  name: スプラチャージャーコラボ
  sub: スプラッシュシールド
  special: トリプルトルネード

splatterscope: &splatterscope
  name: スプラスコープ
  sub: スプラボム
  special: キューインキ

z_f_splatterscope: &z_f_splatterscope
  name: スプラスコープコラボ
  sub: スプラッシュシールド
  special: トリプルトルネード

e_liter_4k: &e_liter_4k
  name: リッター4K
  sub: トラップ
  special: ホップソナー

e_liter_4K_scope: &e_liter_4K_scope
  name: 4Kスコープ
  sub: トラップ
  special: ホップソナー

bamboozler_14_mk_1: &bamboozler_14_mk_1
  name: 14式竹筒銃・甲
  sub: ロボットボム
  special: メガホンレーザー5.1ch

goo_tuber: &goo_tuber
  name: ソイチューバー
  sub: トーピード
  special: マルチミサイル

snipewriter_5h: &snipewriter_5h
  name: R-PEN/5H
  sub: スプリンクラー
  special: エナジースタンド

slosher: &slosher
  name: バケットスロッシャー
  sub: キューバンボム
  special: トリプルトルネード

slosher_deco: &slosher_deco
  name: バケットスロッシャーデコ
  sub: ラインマーカー
  special: ショクワンダー

tri_slocher: &tri_slocher
  name: ヒッセン
  sub: ポイズンミスト
  special: ジェットパック

tri_slosher_nouveau: &tri_slosher_nouveau
  name: ヒッセン・ヒュー
  sub: タンサンボム
  special: エナジースタンド

sloshing_machine: &sloshing_machine
  name: スクリュースロッシャー
  sub: タンサンボム
  special: ナイスダマ

bloblobber: &bloblobber
  name: オーバーフロッシャー
  sub: スプリンクラー
  special: アメフラシ

explosher: &explosher
  name: エクスプロッシャー
  sub: ポイントセンサー
  special: アメフラシ

mini_splatling: &mini_splatling
  name: スプラスピナー
  sub: クイックボム
  special: ウルトラハンコ

zink_mini_splatling: &zink_mini_splatling
  name: スプラスピナーコラボ
  sub: ポイズンミスト
  special: グレートバリア

heavy_splatling: &heavy_splatling
  name: バレルスピナー
  sub: スプリンクラー
  special: ホップソナー

hydra_splatling: &hydra_splatling
  name: ハイドラント
  sub: ロボットボム
  special: ナイスダマ

ballpoint_splatling: &ballpoint_splatling
  name: クーゲルシュライバー
  sub: タンサンボム
  special: ジェットパック

nautilus_47: &nautilus_47
  name: ノーチラス47
  sub: ポイントセンサー
  special: アメフラシ

luna_blaster: &luna_blaster
  name: ノヴァブラスター
  sub: スプラボム
  special: ショクワンダー

luna_blaster_neo: &luna_blaster_neo
  name: ノヴァブラスターネオ
  sub: タンサンボム
  special: ウルトラハンコ

blaster: &blaster
  name: ホットブラスター
  sub: ロボットボム
  special: グレートバリア

range_blaster: &range_blaster
  name: ロングブラスター
  sub: キューバンボム
  special: ホップソナー

clash_blaster: &clash_blaster
  name: クラッシュブラスター
  sub: スプラボム
  special: ウルトラショット

clash_blaster_neo: &clash_blaster_neo
  name: クラッシュブラスターネオ
  sub: カーリングボム
  special: デコイチラシ

rapid_blaster: &rapid_blaster
  name: ラピッドブラスター
  sub: トラップ
  special: トリプルトルネード

rapid_blaster_deco: &rapid_blaster
  name: ラピッドブラスターデコ
  sub: トーピード
  special: ジェットパック

rapid_blaster_pro: &rapid_blaster_pro
  name: Rブラスターエリート
  sub: ポイズンミスト
  special: キューインキ

inkbrush: &inkbrush
  name: パブロ
  sub: スプラボム
  special: メガホンレーザー5.1ch

inkbrush_nouveas: &inkbrush_nouveas
  name: パブロ・ヒュー
  sub: トラップ
  special: ウルトラハンコ

octobrush: &octobrush
  name: ホクサイ
  sub: キューバンボム
  special: ショクワンダー

dapple_dualies: &dapple_dualies
  name: スパッタリー
  sub: ジャンプビーコン
  special: エナジースタンド

dapple_dualies_nouveas: &dapple_dualies_nouveas
  name: スパッタリー・ヒュー
  sub: トーピード
  special: サメライド

splat_dualies: &splat_dualies
  name: スプラマニューバー
  sub: キューバンボム
  special: カニタンク

dark_tetra_dualies: &dark_tetra_dualies
  name: クアッドホッパーブラック
  sub: ロボットボム
  special: サメライド

dualie_squelchers: &dualie_squelchers
  name: デュアルスイーパー
  sub: スプラボム
  special: ホップソナー

glooga_dualies: &glooga_dualies
  name: ケルビン525
  sub: スプラッシュシールド
  special: ナイスダマ

tri_stringer: &tri_stringer
  name: トライストリンガー
  sub: ポイズンミスト
  special: メガホンレーザー5.1ch

reef_lux_450: &reef_lux_450
  name: LACT-450
  sub: カーリングボム
  special: マルチミサイル

splatana_stamper: &splatana_stamper
  name: ジムワイパー
  sub: クイックボム
  special: ショクワンダー

splatana_wiper: &splatana_wiper
  name: ドライブワイパー
  sub: トーピード
  special: ウルトラハンコ
