name: RSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.1", "3.2", "3.3", "3.4", "head"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install Bundler dependencies
        run: bundle install
      - name: Run RSpec
        run: bundle exec rspec
