permissions:
  contents: read
name: Summarize with Gemini

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.title, 'gem')

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --gemfile .github/workflows/summarize/Gemfile

      - name: Run summarization script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_REPO: ${{ github.repository }}
        run: |
          ruby .github/workflows/summarize/app.rb
